# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: protos/puzzlebot_grpc.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    0,
    '',
    'protos/puzzlebot_grpc.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1bprotos/puzzlebot_grpc.proto\x12\x0fRPCPuzzlebotPKG\x1a\x1bgoogle/protobuf/empty.proto\"3\n\rTrailersArray\x12\x0f\n\x03ids\x18\x01 \x03(\x05\x42\x02\x10\x01\x12\x11\n\x05\x62oxes\x18\x02 \x03(\x05\x42\x02\x10\x01\"\x1e\n\x0f\x43ompressedImage\x12\x0b\n\x03img\x18\x01 \x01(\x0c\x32\xa3\x01\n\x0cPuzzlebotRPC\x12K\n\x0fGetTrailersData\x12\x16.google.protobuf.Empty\x1a\x1e.RPCPuzzlebotPKG.TrailersArray\"\x00\x12\x46\n\x08GetImage\x12\x16.google.protobuf.Empty\x1a .RPCPuzzlebotPKG.CompressedImage\"\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'protos.puzzlebot_grpc_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_TRAILERSARRAY'].fields_by_name['ids']._loaded_options = None
  _globals['_TRAILERSARRAY'].fields_by_name['ids']._serialized_options = b'\020\001'
  _globals['_TRAILERSARRAY'].fields_by_name['boxes']._loaded_options = None
  _globals['_TRAILERSARRAY'].fields_by_name['boxes']._serialized_options = b'\020\001'
  _globals['_TRAILERSARRAY']._serialized_start=77
  _globals['_TRAILERSARRAY']._serialized_end=128
  _globals['_COMPRESSEDIMAGE']._serialized_start=130
  _globals['_COMPRESSEDIMAGE']._serialized_end=160
  _globals['_PUZZLEBOTRPC']._serialized_start=163
  _globals['_PUZZLEBOTRPC']._serialized_end=326
# @@protoc_insertion_point(module_scope)
