ARG BASE_IMAGE
FROM ${BASE_IMAGE}

ENV DEBIAN_FRONTEND=noninteractive
ARG CUDA_VERSION="cpu"

COPY docker/install_torch.sh /tmp/install_torch.sh --cuda-version=${CUDA_VERSION}
RUN /tmp/install_torch.sh